# Generated by Django 3.1.7 on 2021-03-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='creating_at',
            new_name='created_at',
        ),
    ]
