# Generated by Django 3.1.7 on 2021-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_x_offset',
            field=models.IntegerField(default=0, verbose_name='Смещение фотографии по оси x'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_y_offset',
            field=models.IntegerField(default=0, verbose_name='Смещение фотографии по оси y'),
        ),
    ]
