# Generated by Django 3.1.7 on 2021-03-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='movie',
            new_name='post',
        ),
    ]
