# Generated by Django 3.1.7 on 2021-03-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210307_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='lorem ipsum', verbose_name='Полное описание работы'),
            preserve_default=False,
        ),
    ]
