# Generated by Django 3.1.7 on 2021-03-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image_x_offset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-serial_number', '-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='serial_number',
            field=models.IntegerField(default=1, max_length=255, verbose_name='Приоритет при выдаче'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Подпись к фотографии'),
        ),
    ]
