# Generated by Django 3.1.7 on 2021-04-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210331_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['serial_number', '-created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='serial_number',
            field=models.IntegerField(default=1, verbose_name='Приоритет при выдаче'),
        ),
    ]
