# Generated by Django 3.1.7 on 2021-03-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210314_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='description',
        ),
    ]
